name: meshal_doctor_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # go router
  go_router: ^17.0.0

  # bloc
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # get it
  get_it: ^9.0.5

  # flutter svg
  flutter_svg: ^2.2.2

  # graphql flutter
  graphql_flutter: ^5.2.1

  # logger
  logger: ^2.6.2

  # flutter localization
  flutter_localization: ^0.3.3

  # intl phone field
  intl_phone_field: ^3.2.0

  # pinput
  pinput: ^5.0.2

  # cached network image
  cached_network_image: ^3.4.1

  # dropdown btn 2
  dropdown_button2: ^2.3.9

  # url launcher
  url_launcher: ^6.3.2

  # intl
  intl: ^0.20.2

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # skeletonizer:
  skeletonizer: ^2.1.0+1

  # delightful_toast:
  delightful_toast: ^1.1.0

  # connectivity_plus
  connectivity_plus: ^6.1.3

  # chat bubbles
  chat_bubbles: ^1.7.0

  # badges
  badges: ^3.1.2

  # image picker
  image_picker: ^1.2.1

  # flutter image compress
  flutter_image_compress: ^2.4.0

  # package info plus
  package_info_plus: ^9.0.0

  # firebase
  firebase_core: ^4.2.1

  # firebase messaging
  firebase_messaging: ^16.0.4

  # flutter local notifications
  flutter_local_notifications: ^19.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # change app package name
  change_app_package_name: ^1.5.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/png/
    - assets/images/jpeg/
    - assets/icons/svg/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

